# Generated by Django 3.2.10 on 2021-12-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genreId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('artistName', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('releaseDate', models.CharField(max_length=50)),
                ('kind', models.CharField(max_length=50)),
                ('artistId', models.CharField(max_length=50)),
                ('artistUrl', models.CharField(max_length=100)),
                ('contentAdvisoryRating', models.CharField(max_length=100)),
                ('artworkUrl100', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('genres', models.ManyToManyField(to='api.Genre')),
            ],
        ),
    ]
