# Generated by Django 3.2.10 on 2021-12-10 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='genres',
            field=models.ManyToManyField(related_name='genres', to='api.Genre'),
        ),
        migrations.AlterField(
            model_name='track',
            name='id',
            field=models.PositiveIntegerField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
